CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INTO STUDENT(ROLL_NO,NAME,ADDRESS,PHONE,AGE)VALUES
('1','RAM','DEHLI','******',18),
('2','RAMESH','GURGAON','******',18),
('3','SUJIT','ROHTAK','******',20),
('4','SURESH','DEHLI','******',18),
('5','AMAN','GURGAON','******',20),
('6','HARSH','ROHTAK','******',18);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE =18 AND ADDRESS='DEHLI';
SELECT * FROM STUDENT WHERE AGE =18 AND NAME='RAM';
SELECT * FROM STUDENT WHERE NAME='RAM' OR NAME='SUJIT';
SELECT * FROM STUDENT WHERE AGE=18 AND(NAME='RAM' OR NAME='RAMESH');